// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/tuanpnt17/kumo-classroom-be/internal/controllers"
	"github.com/tuanpnt17/kumo-classroom-be/internal/repositories"
	"github.com/tuanpnt17/kumo-classroom-be/internal/usecases"
)

// Injectors from injectors.go:

func InitAuthController() *controllers.AuthController {
	iUnitOfWork := repositories.NewUnitOfWork()
	iUserRepository := repositories.NewUserRepository(iUnitOfWork)
	iLoginUsecase := usecases.NewLoginUsecase(iUserRepository)
	authController := controllers.NewAuthController(iLoginUsecase)
	return authController
}
