// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/tuanpnt17/kumo-classroom-be/internal/controllers"
	"github.com/tuanpnt17/kumo-classroom-be/internal/repositories"
	"github.com/tuanpnt17/kumo-classroom-be/internal/services"
)

// Injectors from injectors.go:

func InitUserController() *controllers.UserController {
	iUserRepository := repositories.NewUserRepository()
	iUserService := services.NewUserService(iUserRepository)
	userController := controllers.NewUserController(iUserService)
	return userController
}
